spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: notification_user
    password: 12345
    driver-class-name: org.postgresql.Driver

server:
  port: 8085
